#' @title Universal Spatial Data Loader and 4-Stage Diagnostic Profiler
#' @description Automatically detects and loads spatial files (.shp, .geojson, .tif)
#' using 'sf' or 'terra'. It generates a comprehensive 4-stage diagnostic profile
#' (Base Geometry, Bounding Box/Centroid, Attribute Preview, Topology Health)
#' to ensure geospatial data integrity before epidemiological modeling.
#'
#' @param filepath Character. The full path to the spatial file.
#' @param plot_preview Logical. If TRUE, generates the 4-stage diagnostic plots.
#' @param check_invalid Logical. If TRUE, performs topology validation.
#' @param color_palette Character. Name of the RColorBrewer palette (default: "YlOrRd").
#' @param reverse_palette Logical. If TRUE, reverses the color palette vector.
#' @param legend Logical. If TRUE, displays the legend on applicable plots.
#' @param legend_position Character. Legend position (e.g., "bottom", "bottomright").
#' @param legend_orientation Character. "vertical" or "horizontal".
#' @param footer Logical. If TRUE, adds a reproducible footer at the bottom center.
#' @param save_plot Logical. If TRUE, saves all 4 plots as high-resolution PNGs.
#' @param save_prefix Character. Prefix for output files.
#' @param res Numeric. Resolution in DPI for the saved 4K plot (default: 300).
#'
#' @return An object of class 'sf' (vector) or 'SpatRaster' (raster).
#' @export
#'
#' @examples
#' \dontrun{
#' # Load a shapefile and generate 4 diagnostic plots in 4K
#' my_spatial_data <- A1_loadspatial(
#'   filepath = "data/endemic_districts.shp",
#'   plot_preview = TRUE,
#'   save_plot = TRUE,
#'   save_prefix = "EpiNode_Check"
#' )
#' }
A1_loadspatial <- function(filepath,
                           plot_preview = TRUE,
                           check_invalid = TRUE,
                           color_palette = "YlOrRd",
                           reverse_palette = FALSE,
                           legend = TRUE,
                           legend_position = "bottomright",
                           legend_orientation = "vertical",
                           footer = TRUE,
                           save_plot = FALSE,
                           save_prefix = "A1_loadspatial",
                           res = 300) {

  # 1. Input Validation
  if (!is.character(filepath) || length(filepath) != 1) {
    stop("AFRIN Error: 'filepath' must be a single character string.", call. = FALSE)
  }
  if (!file.exists(filepath)) {
    stop(paste("AFRIN Error: File not found at", filepath), call. = FALSE)
  }

  # 2. File Extension Detection
  ext <- tolower(tools::file_ext(filepath))
  is_vector <- ext %in% c("shp", "geojson")
  is_raster <- ext %in% c("tif", "tiff")

  if (!is_vector && !is_raster) {
    stop("AFRIN Error: Unsupported file format. Use .shp, .geojson, or .tif.", call. = FALSE)
  }

  # 3. Load Engine Check (Hidden Dependencies)
  spatial_obj <- NULL

  if (is_vector) {
    if (!requireNamespace("sf", quietly = TRUE)) {
      stop("AFRIN Error: Package 'sf' is required for vector data.", call. = FALSE)
    }
    spatial_obj <- sf::st_read(filepath, quiet = TRUE)
  } else if (is_raster) {
    if (!requireNamespace("terra", quietly = TRUE)) {
      stop("AFRIN Error: Package 'terra' is required for raster data.", call. = FALSE)
    }
    spatial_obj <- terra::rast(filepath)
  }

  # 4. Diagnostic Profiling Generation
  if (plot_preview) {

    timestamp <- format(Sys.time(), "%Y%m%d_%H%M%S")
    footer_text <- paste0("Generated by R-Studio (", R.version.string,
                          ") on ", format(Sys.time(), "%B %d, %Y at %H:%M:%S"))

    # Setup Palette
    pal_vector <- NULL
    if (requireNamespace("RColorBrewer", quietly = TRUE) &&
        color_palette %in% rownames(RColorBrewer::brewer.pal.info)) {
      n_col <- RColorBrewer::brewer.pal.info[color_palette, "maxcolors"]
      pal_vector <- RColorBrewer::brewer.pal(n_col, color_palette)
    } else {
      pal_vector <- grDevices::heat.colors(9)
    }
    if (reverse_palette) {
      pal_vector <- rev(pal_vector)
    }

    # Internal Function to Handle Plot Saving & Layout
    generate_plot <- function(plot_expr, suffix, title) {
      if (save_plot) {
        filename <- paste0(save_prefix, "_A1_loadspatial_", timestamp, "_", suffix, ".png")
        grDevices::png(filename = filename, width = 3840, height = 2160, res = res)
      }

      # Margins Strategy (Outer Margin for Footer to prevent overlap)
      old_par <- graphics::par(no.readonly = TRUE)
      oma_bottom <- ifelse(footer, 6, 2)
      graphics::par(oma = c(oma_bottom, 2, 3, 2), mar = c(4, 4, 4, 4))

      # Evaluate Plot
      eval(plot_expr)
      graphics::title(main = paste("AFRIN Diagnostic:", title), outer = TRUE, line = 0)

      # Strict Footer Placement
      if (footer) {
        graphics::mtext(footer_text, side = 1, line = 4, adj = 0.5,
                        outer = TRUE, col = "darkgray", cex = 0.8)
      }

      if (save_plot) {
        grDevices::dev.off()
        message(paste("AFRIN Note: Saved", filename))
      }

      # Restore par settings
      graphics::par(old_par)
    }

    # VECTOR PROFILING
    if (is_vector) {

      # Plot 1: Base Geometry
      generate_plot(expression({
        graphics::plot(sf::st_geometry(spatial_obj), col = "#E0E0E0", border = "#555555")
      }), "1_Base", "Base Geometry Network")

      # Plot 2: Bounding Box & Centroid
      generate_plot(expression({
        bb <- sf::st_as_sfc(sf::st_bbox(spatial_obj))
        cents <- suppressWarnings(sf::st_centroid(spatial_obj))
        graphics::plot(sf::st_geometry(bb), col = NA, border = "blue", lty = 2, lwd = 3)
        graphics::plot(sf::st_geometry(spatial_obj), col = "#F5F5F5", border = "darkgrey", add = TRUE)
        graphics::plot(sf::st_geometry(cents), col = "red", pch = 16, cex = 1.2, add = TRUE)
        if (legend) {
          horiz <- ifelse(legend_orientation == "horizontal", TRUE, FALSE)
          graphics::legend(legend_position, legend = c("Bounding Box", "Centroids"),
                           col = c("blue", "red"), lty = c(2, NA), pch = c(NA, 16),
                           lwd = c(3, NA), bty = "n", horiz = horiz)
        }
      }), "2_Extent", "Spatial Extent & Centroid Distribution")

      # Plot 3: Attribute Preview (First Numeric)
      generate_plot(expression({
        num_cols <- sapply(sf::st_drop_geometry(spatial_obj), is.numeric)
        if (any(num_cols)) {
          first_num <- names(num_cols)[num_cols][1]
          vals <- spatial_obj[[first_num]]

          # 5-class categorization for Base R plotting
          qts <- stats::quantile(vals, probs = seq(0, 1, 0.2), na.rm = TRUE)
          if (length(unique(qts)) > 1) {
            cats <- cut(vals, breaks = unique(qts), include.lowest = TRUE)
            pal_ramp <- grDevices::colorRampPalette(pal_vector)(length(levels(cats)))
            graphics::plot(sf::st_geometry(spatial_obj), col = pal_ramp[as.numeric(cats)], border = "white")

            if (legend) {
              horiz <- ifelse(legend_orientation == "horizontal", TRUE, FALSE)
              graphics::legend(legend_position, legend = levels(cats), fill = pal_ramp,
                               title = first_num, bty = "n", horiz = horiz)
            }
          } else {
            graphics::plot(sf::st_geometry(spatial_obj), col = pal_vector[1])
            graphics::mtext("Data is homogenous", side = 3, line = -1)
          }
        } else {
          graphics::plot(sf::st_geometry(spatial_obj), col = "grey")
          graphics::mtext("No numeric attribute found for preview", side = 3, line = -1, col = "red")
        }
      }), "3_Attribute", "First Numeric Attribute Preview")

      # Plot 4: Topology Health Flag
      generate_plot(expression({
        graphics::plot(sf::st_geometry(spatial_obj), col = "#333333", border = "#555555")
        if (check_invalid) {
          validity <- sf::st_is_valid(spatial_obj)
          if (any(!validity, na.rm = TRUE)) {
            graphics::plot(sf::st_geometry(spatial_obj[!validity, ]),
                           col = "red", border = "yellow", lwd = 2, add = TRUE)
            graphics::mtext("WARNING: Invalid Geometries Detected (Marked in RED)",
                            side = 3, line = -1, col = "red", font = 2)
          } else {
            graphics::mtext("Topology Check Passed: All Valid",
                            side = 3, line = -1, col = "green", font = 2)
          }
        }
      }), "4_Topology", "Topology Health & Invalid Flags")

    } else if (is_raster) {
      # RASTER PROFILING
      pal_ramp <- grDevices::colorRampPalette(pal_vector)(100)

      generate_plot(expression({
        terra::plot(spatial_obj, col = pal_ramp, axes = TRUE)
      }), "1_RasterBase", "Continuous Raster Heatmap")

      generate_plot(expression({
        ext_poly <- terra::ext(spatial_obj)
        graphics::plot(ext_poly, col = NA, border = "blue", lwd = 3, lty = 2)
        terra::plot(spatial_obj, col = "#F0F0F0", add = TRUE, legend = FALSE)
      }), "2_RasterExtent", "Raster Extent Bounding Box")

      generate_plot(expression({
        terra::contour(spatial_obj, col = pal_vector[length(pal_vector)], lwd = 1.5)
      }), "3_RasterContour", "Topological Contour Extraction")

      generate_plot(expression({
        med_val <- stats::median(terra::values(spatial_obj), na.rm = TRUE)
        bin_rast <- spatial_obj > med_val
        terra::plot(bin_rast, col = c("#E0E0E0", "red"), axes = TRUE, legend = legend)
        graphics::mtext("Red indicates values above global median", side = 3, line = -1)
      }), "4_RasterMedian", "Above-Median Outlier Check")
    }
  }

  message("AFRIN Note: Spatial data loaded successfully.")
  return(invisible(spatial_obj))
}
