#' @title Spatial Intelligence Node Finder and Suitability Profiling
#' @description Automatically identifies the optimal locations (Nodes) for new healthcare
#' facilities or quarantine centers based on spatial gravity (local disease burden +
#' neighborhood disease burden). Generates a 4-panel diagnostic profile including
#' Gravity Mass, Suitability Heatmap, Tactical Isolation, and Hub-and-Spoke allocation.
#'
#' @param spatial_data An object of class 'sf' containing polygon geometries.
#' @param var_col Character. The disease burden column (e.g., cases, prevalence). Auto-coerced if character.
#' @param top_n Numeric. The number of top candidate nodes to identify (default: 3).
#' @param neighbor_weight Numeric. The weight given to neighbor's disease burden (default: 0.5).
#' @param color_palette Character. RColorBrewer palette name (default: "YlOrRd").
#' @param reverse_palette Logical. If TRUE, reverses the color palette.
#' @param legend Logical. If TRUE, displays legends.
#' @param legend_position Character. Legend position (default: "bottom").
#' @param legend_orientation Character. "vertical" or "horizontal" layout.
#' @param footer Logical. If TRUE, adds a reproducible footer at the bottom center.
#' @param save_plot Logical. If TRUE, saves 4 high-resolution 4K PNG plots.
#' @param save_prefix Character. Prefix for output files.
#' @param res Numeric. Resolution in DPI for the saved plot (default is 300).
#'
#' @return A list containing the ranked candidate nodes, distance allocations,
#' and the appended 'sf' object invisibly.
#' @export
#'
#' @examples
#' \dontrun{
#' # Find the top 3 best districts to build a new Malaria Referral Hospital
#' optimal_nodes <- B4_IntelligenceNodeFinder(
#'   spatial_data = df_jateng,
#'   var_col = "MALARIA",
#'   top_n = 3,
#'   save_plot = TRUE,
#'   save_prefix = "Malaria_Node_Strategy"
#' )
#' }
B4_IntelligenceNodeFinder <- function(spatial_data,
                                      var_col,
                                      top_n = 3,
                                      neighbor_weight = 0.5,
                                      color_palette = "YlOrRd",
                                      reverse_palette = FALSE,
                                      legend = TRUE,
                                      legend_position = "bottom",
                                      legend_orientation = "vertical",
                                      footer = TRUE,
                                      save_plot = FALSE,
                                      save_prefix = "B4_NodeFinder",
                                      res = 300) {

  # 1. Strict Validation & sf Check
  if (!requireNamespace("sf", quietly = TRUE)) {
    stop("AFRIN Error: Package 'sf' is required.", call. = FALSE)
  }
  if (!inherits(spatial_data, "sf")) stop("AFRIN Error: 'spatial_data' must be an 'sf' object.", call. = FALSE)
  if (!(var_col %in% names(spatial_data))) stop(paste("AFRIN Error: Column", var_col, "not found."), call. = FALSE)

  # 2. Auto-Coercion Engine
  raw_var <- spatial_data[[var_col]]
  if (!is.numeric(raw_var)) {
    warning(paste("AFRIN Warning: 'var_col' (", var_col, ") is not numeric. Auto-coercing..."), call. = FALSE)
    num_var <- suppressWarnings(as.numeric(as.character(raw_var)))
    num_var[is.na(num_var)] <- 0
    spatial_data[[var_col]] <- num_var
  }

  var_vals <- spatial_data[[var_col]]
  n <- length(var_vals)

  if (top_n >= n) top_n <- max(1, n - 1)

  # 3. Spatial Gravity Calculation (Base sf & Matrix Algebra)
  message("AFRIN Note: Computing Spatial Gravity and Neighbor Influences...")
  cents <- suppressWarnings(sf::st_centroid(spatial_data))
  coords <- sf::st_coordinates(cents)

  # Queen Contiguity Matrix
  touch_list <- sf::st_touches(spatial_data, sparse = FALSE)
  W_bin <- matrix(as.numeric(touch_list), nrow = n, ncol = n)

  # Calculate Suitability Score: Local Case + (Neighbor Weight * Sum of Neighbor Cases)
  neighbor_burden <- as.numeric(W_bin %*% var_vals)
  suitability_score <- var_vals + (neighbor_weight * neighbor_burden)

  spatial_data[["Suitability_Score"]] <- suitability_score
  spatial_data[["Node_Rank"]] <- rank(-suitability_score, ties.method = "first")
  spatial_data[["Is_Top_Candidate"]] <- spatial_data[["Node_Rank"]] <= top_n

  top_candidates <- spatial_data[spatial_data[["Is_Top_Candidate"]], ]
  top_cents <- cents[spatial_data[["Is_Top_Candidate"]], ]

  # 4. Catchment Allocation (Hub-and-Spoke via Distance Matrix)
  dist_matrix <- sf::st_distance(cents, top_cents)
  nearest_idx <- apply(dist_matrix, 1, which.min)

  # 5. High-Res Visualization Engine
  timestamp <- format(Sys.time(), "%Y%m%d_%H%M%S")
  footer_text <- paste0("Generated by R-Studio (", R.version.string, ") on ", format(Sys.time(), "%B %d, %Y at %H:%M:%S"))

  # Palette Prep
  pal_colors <- NULL
  if (requireNamespace("RColorBrewer", quietly = TRUE) && color_palette %in% rownames(RColorBrewer::brewer.pal.info)) {
    pal_colors <- RColorBrewer::brewer.pal(RColorBrewer::brewer.pal.info[color_palette, "maxcolors"], color_palette)
  } else {
    pal_colors <- grDevices::heat.colors(7)
  }
  if (reverse_palette) pal_colors <- rev(pal_colors)
  pal_func <- grDevices::colorRampPalette(pal_colors)

  generate_plot <- function(plot_expr, suffix, title, dark_mode = FALSE) {
    if (save_plot) {
      filename <- paste0(save_prefix, "_", timestamp, "_", suffix, ".png")
      grDevices::png(filename = filename, width = 3840, height = 2160, res = res)
    }

    old_par <- graphics::par(no.readonly = TRUE)
    oma_bottom <- ifelse(footer, 6, 2)

    if (dark_mode) {
      graphics::par(oma = c(oma_bottom, 2, 3, 2), mar = c(4, 4, 3, 2), bg = "#1E1E1E", fg = "white", col.main = "white")
    } else {
      graphics::par(oma = c(oma_bottom, 2, 3, 2), mar = c(4, 4, 3, 2), bg = "white", fg = "black", col.main = "black")
    }

    eval(plot_expr)
    graphics::title(main = paste("AFRIN:", title), outer = TRUE, line = 0, cex.main = 1.5)

    if (footer) {
      graphics::mtext(footer_text, side = 1, line = 4, adj = 0.5, outer = TRUE, col = ifelse(dark_mode, "gray", "darkgray"), cex = 0.8)
    }

    if (save_plot) {
      grDevices::dev.off()
      message(paste("AFRIN Note: Saved", filename))
    }
    graphics::par(old_par)
  }

  # PLOT 1: Spatial Gravity / Disease Mass Plot
  generate_plot(expression({
    graphics::plot(sf::st_geometry(spatial_data), col = "#F0F0F0", border = "#B0B0B0")

    # Bubble sizing logic
    max_val <- max(var_vals, na.rm = TRUE)
    if (max_val > 0) {
      radii <- sqrt(var_vals / max_val) * 0.3 # Max inch scale
      graphics::symbols(x = coords[, 1], y = coords[, 2], circles = radii,
                        inches = 0.25, add = TRUE, bg = grDevices::rgb(0.8, 0.2, 0.2, 0.6),
                        fg = "darkred", lwd = 1.5)
    }

    if (legend) {
      graphics::legend(legend_position, legend = "Disease Burden Volume (Bubble)",
                       pch = 21, pt.bg = grDevices::rgb(0.8, 0.2, 0.2, 0.6), col = "darkred",
                       bty = "n", xpd = NA)
    }
  }), "1_DiseaseMass", "Spatial Gravity & Disease Mass Distribution")

  # PLOT 2: Node Suitability Heatmap
  generate_plot(expression({
    brks <- unique(stats::quantile(suitability_score, probs = seq(0, 1, length.out = 6), na.rm = TRUE))
    if (length(brks) > 1) {
      cats <- cut(suitability_score, breaks = brks, include.lowest = TRUE)
      cols_mapped <- pal_func(length(levels(cats)))[as.numeric(cats)]
      lgd_labels <- levels(cats)
      lgd_cols <- pal_func(length(levels(cats)))
    } else {
      cols_mapped <- rep(pal_colors[3], n)
      lgd_labels <- "Homogeneous"
      lgd_cols <- pal_colors[3]
    }

    graphics::plot(sf::st_geometry(spatial_data), col = cols_mapped, border = "#555555", lwd = 0.5)

    # Highlight top candidates
    graphics::plot(sf::st_geometry(top_cents), pch = 23, bg = "black", col = "white", cex = 2, add = TRUE)

    if (legend) {
      horiz <- ifelse(legend_orientation == "horizontal", TRUE, FALSE)
      graphics::legend(legend_position, legend = c(lgd_labels, "Selected Nodes"),
                       fill = c(lgd_cols, NA), border = c(rep("black", length(lgd_cols)), NA),
                       pch = c(rep(NA, length(lgd_cols)), 23), pt.bg = c(rep(NA, length(lgd_cols)), "black"),
                       col = c(rep(NA, length(lgd_cols)), "white"), bty = "n", horiz = horiz, xpd = NA, cex = 0.9)
    }
  }), "2_SuitabilityMap", "Node Suitability Heatmap (Local + Neighbor Gravity)")

  # PLOT 3: Top Candidates Isolation Map (Dark Mode)
  generate_plot(expression({
    iso_cols <- ifelse(spatial_data[["Is_Top_Candidate"]], "#2ECC71", "#2C3E50")
    graphics::plot(sf::st_geometry(spatial_data), col = iso_cols, border = "#111111", lwd = 1)

    if (legend) {
      graphics::legend(legend_position, legend = paste("Top", top_n, "Strategic Nodes"),
                       fill = "#2ECC71", border = "#111111", bty = "n", text.col = "white", xpd = NA)
    }
  }), "3_IsolationMap", paste("Top", top_n, "Strategic Healthcare Node Candidates"), dark_mode = TRUE)

  # PLOT 4: Optimal Hub-and-Spoke Map
  generate_plot(expression({
    graphics::plot(sf::st_geometry(spatial_data), col = "#FAFAFA", border = "#E0E0E0")
    top_coords <- sf::st_coordinates(top_cents)

    # Draw Spoke lines
    for (i in seq_len(n)) {
      target_idx <- nearest_idx[i]
      graphics::segments(coords[i, 1], coords[i, 2], top_coords[target_idx, 1], top_coords[target_idx, 2],
                         col = grDevices::rgb(0.2, 0.4, 0.8, 0.4), lwd = 1.5)
    }

    # Plot Hubs
    graphics::plot(sf::st_geometry(top_cents), pch = 21, bg = "red", col = "black", cex = 2.5, add = TRUE)
    # Plot spokes/satellites
    graphics::plot(sf::st_geometry(cents), pch = 20, col = "#2C3E50", cex = 0.8, add = TRUE)

    if (legend) {
      horiz <- ifelse(legend_orientation == "horizontal", TRUE, FALSE)
      graphics::legend(legend_position, legend = c("Node / Hub", "Satellite / Origin", "Referral Pathway"),
                       pt.bg = c("red", NA, NA), col = c("black", "#2C3E50", grDevices::rgb(0.2, 0.4, 0.8, 0.6)),
                       pch = c(21, 20, NA), lty = c(NA, NA, 1), lwd = c(NA, NA, 2), bty = "n", horiz = horiz, xpd = NA)
    }
  }), "4_HubAndSpoke", "Optimal Hub-and-Spoke Catchment Network")

  # 6. Compilation
  res_list <- list(
    Top_Nodes_Ranked = sf::st_drop_geometry(top_candidates)[, c("Node_Rank", var_col, "Suitability_Score")],
    spatial_data_appended = spatial_data
  )

  message("AFRIN Note: Intelligence Node Finder completed successfully.")
  return(invisible(res_list))
}
